networks:
  mcp-network:
    driver: bridge
services:
  # MCP Server with IT Tools functionality
  it-tools-mcp:
    build: .
    container_name: it-tools-mcp-server
    environment:
      - NODE_ENV=production
    networks:
      - mcp-network
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /tmp:/tmp
