version: '3.8'
networks:
  mcp-network:
    driver: bridge
services:
  it-tools-mcp:
    image: it-tools-mcp:latest
    container_name: it-tools-mcp-production
    environment:
      - NODE_ENV=production
    networks:
      - mcp-network
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /tmp:/tmp
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('healthy')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
