version: '3.8'
services:
  it-tools-mcp:
    image: wrenchpilot/it-tools-mcp:latest
    container_name: it-tools-mcp
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=production
    # Uncomment if you need to persist data
    # volumes:
    #   - ./data:/app/data
    # Uncomment if you need to expose ports
    # ports:
    #   - "3000:3000"
networks:
  default:
    driver: bridge
